# Generated by Django 3.1.1 on 2020-10-20 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_actuator', models.CharField(max_length=100, null=True)),
                ('type_actuator', models.CharField(max_length=100, null=True)),
                ('model_actuator', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('port_actuator', models.CharField(max_length=100, null=True)),
                ('description_port', models.TextField(max_length=2000, null=True)),
                ('active_status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MicroController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_controller', models.CharField(max_length=200, null=True)),
                ('model_controller', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('mac', models.CharField(max_length=20, null=True)),
                ('chip_id', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='Controlador Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_sensor', models.CharField(max_length=100, null=True)),
                ('type_sensor', models.CharField(max_length=100, null=True)),
                ('model_sensor', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('port_sensor', models.CharField(max_length=100, null=True)),
                ('description_port', models.TextField(max_length=2000, null=True)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id_controller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.microcontroller')),
            ],
        ),
        migrations.CreateModel(
            name='SensorConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_config_sensor', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('time_read_sensor', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id_sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sector', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('id_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.project')),
            ],
        ),
        migrations.AddField(
            model_name='microcontroller',
            name='id_sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.sector'),
        ),
        migrations.CreateModel(
            name='DataSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=100, null=True)),
                ('data_type', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('id_controller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.microcontroller')),
                ('id_sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='DataActuador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False)),
                ('value', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id_actuator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.actuator')),
                ('id_controller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.microcontroller')),
            ],
        ),
        migrations.CreateModel(
            name='ActuatorConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_config_actuator', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id_actuator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.actuator')),
            ],
        ),
        migrations.AddField(
            model_name='actuator',
            name='id_controller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.microcontroller'),
        ),
    ]
