# Generated by Django 3.1.1 on 2020-10-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasensor',
            name='id_controller',
        ),
        migrations.RemoveField(
            model_name='datasensor',
            name='id_sensor',
        ),
        migrations.DeleteModel(
            name='DataActuador',
        ),
        migrations.DeleteModel(
            name='DataSensor',
        ),
    ]
