# Generated by Django 3.1.1 on 2020-10-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201027_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actuator',
            old_name='id_controller',
            new_name='controller',
        ),
        migrations.RenameField(
            model_name='actuatorconfiguration',
            old_name='id_actuator',
            new_name='actuator',
        ),
        migrations.RenameField(
            model_name='microcontroller',
            old_name='id_sector',
            new_name='sector',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='id_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='id_controller',
            new_name='controller',
        ),
        migrations.RenameField(
            model_name='sensorconfiguration',
            old_name='id_sensor',
            new_name='sensor',
        ),
    ]
