# Generated by Django 3.1.1 on 2021-05-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20201028_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='send_message',
            field=models.BooleanField(default=False, verbose_name='Monitorar via Telegram?'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='send_message',
            field=models.BooleanField(default=False, verbose_name='Monitorar via Telegram?'),
        ),
    ]
