# Generated by Django 3.2.5 on 2021-07-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210513_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorconfiguration',
            name='sensor',
        ),
        migrations.AlterModelOptions(
            name='actuator',
            options={'verbose_name': 'Atuador', 'verbose_name_plural': '5 - Atuador'},
        ),
        migrations.AlterModelOptions(
            name='microcontroller',
            options={'verbose_name': 'Microcontrolador', 'verbose_name_plural': '3 - Microcontrolador'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projeto', 'verbose_name_plural': '1 - Projeto'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Setor', 'verbose_name_plural': '2 - Setor'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Sensor', 'verbose_name_plural': '4 - Sensor'},
        ),
        migrations.DeleteModel(
            name='ActuatorConfiguration',
        ),
        migrations.DeleteModel(
            name='SensorConfiguration',
        ),
    ]
