# Generated by Django 3.1.1 on 2021-02-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitor', '0002_delete_scheduleaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_schedule', models.CharField(max_length=100, null=True)),
                ('min_start', models.CharField(default='*', max_length=10, null=True)),
                ('hours_start', models.CharField(default='*', max_length=10, null=True)),
                ('day_start', models.CharField(default='*', max_length=10, null=True)),
                ('month_start', models.CharField(default='*', max_length=10, null=True)),
                ('week_start', models.CharField(default='*', max_length=10, null=True)),
                ('min_end', models.CharField(default='*', max_length=10, null=True)),
                ('hours_end', models.CharField(default='*', max_length=10, null=True)),
                ('day_end', models.CharField(default='*', max_length=10, null=True)),
                ('month_end', models.CharField(default='*', max_length=10, null=True)),
                ('week_end', models.CharField(default='*', max_length=10, null=True)),
                ('actions_end', models.ManyToManyField(related_name='tag_schedule2', to='monitor.Action')),
                ('actions_start', models.ManyToManyField(related_name='tag_schedule', to='monitor.Action')),
            ],
        ),
    ]
