# Generated by Django 3.1.1 on 2021-03-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0002_auto_20210317_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='Agendamento Conforme padrão CronTab'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.CharField(default='* * * * *', max_length=30, null=True, verbose_name='Agendamento Conforme padrão CronTab'),
        ),
    ]
