# Generated by Django 3.1.1 on 2021-03-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20210317_1151'),
        ('Agenda', '0004_auto_20210317_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='actions_end',
            field=models.ManyToManyField(null=True, related_name='tag_schedule2', to='monitor.Action'),
        ),
    ]
