# Generated by Django 3.1.1 on 2021-03-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20210317_1151'),
        ('Agenda', '0005_auto_20210317_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='actions_end',
            field=models.ManyToManyField(related_name='tag_schedule2', to='monitor.Action'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Agendamento Conforme padrão CronTab'),
        ),
    ]
