# Generated by Django 3.2.5 on 2021-07-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20210712_1417'),
        ('Agenda', '0007_auto_20210317_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Agenda', 'verbose_name_plural': '1 - Agenda'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='actions_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='actions_start',
            field=models.ManyToManyField(related_name='tag_schedule', to='monitor.Action', verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.CharField(default='* * * * *', help_text='Padrão CronTab', max_length=30, null=True, verbose_name='Agendamento'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tag_schedule',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
