# Generated by Django 3.1.1 on 2020-10-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_action', models.CharField(max_length=100, null=True)),
                ('new_status', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('actuator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.actuator')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_rule', models.CharField(max_length=100, null=True)),
                ('condition', models.CharField(choices=[('1', '>'), ('2', '≥'), ('3', '<'), ('4', '≤'), ('5', '='), ('6', '!=')], max_length=1)),
                ('value', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_schedule', models.CharField(max_length=100, null=True)),
                ('new_status', models.CharField(max_length=100, null=True)),
                ('time_value', models.CharField(max_length=100, null=True)),
                ('after_status', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('actuator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.actuator')),
            ],
        ),
        migrations.CreateModel(
            name='RulesMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_monitor', models.CharField(max_length=100, null=True)),
                ('actionsFalse', models.ManyToManyField(related_name='tag_monitor2', to='monitor.Action')),
                ('actionsTrue', models.ManyToManyField(related_name='tag_monitor', to='monitor.Action')),
                ('rules', models.ManyToManyField(related_name='tag_monitor', to='monitor.Rule')),
            ],
        ),
    ]
