# Generated by Django 3.1.1 on 2021-02-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleAction',
        ),
    ]
