# Generated by Django 3.1.1 on 2021-03-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_delete_scheduleaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='new_status',
            field=models.CharField(max_length=100, null=True, verbose_name='Status (1-True; 0-False)'),
        ),
    ]
