# Generated by Django 3.1.1 on 2021-04-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20210317_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='new_status',
        ),
        migrations.AddField(
            model_name='action',
            name='data',
            field=models.CharField(max_length=200, null=True, verbose_name='Json Format'),
        ),
    ]
