# Generated by Django 3.1.1 on 2021-04-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20210421_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='data',
            field=models.CharField(max_length=200, null=True, verbose_name='Data in Json Format'),
        ),
    ]
