# Generated by Django 3.2.5 on 2021-07-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20210423_0812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Ação', 'verbose_name_plural': '2 - Ações'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'Regra', 'verbose_name_plural': '1 - Regras'},
        ),
        migrations.AlterModelOptions(
            name='rulesmonitor',
            options={'verbose_name': 'Monitor', 'verbose_name_plural': '3 - Monitores'},
        ),
        migrations.RemoveField(
            model_name='rulesmonitor',
            name='actionsFalse',
        ),
        migrations.AlterField(
            model_name='action',
            name='data',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Data in Json Format'),
        ),
        migrations.AlterField(
            model_name='action',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='tag_rule',
            field=models.CharField(max_length=100, null=True, verbose_name='Regra'),
        ),
        migrations.AlterField(
            model_name='rulesmonitor',
            name='actionsTrue',
            field=models.ManyToManyField(related_name='tag_monitor', to='monitor.Action', verbose_name='Ações'),
        ),
        migrations.AlterField(
            model_name='rulesmonitor',
            name='rules',
            field=models.ManyToManyField(related_name='tag_monitor', to='monitor.Rule', verbose_name='Regras'),
        ),
        migrations.AlterField(
            model_name='rulesmonitor',
            name='tag_monitor',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
