# Generated by Django 3.1.1 on 2020-10-27 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201027_2223'),
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=100, null=True)),
                ('data_type', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('id_controller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.microcontroller')),
                ('id_sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='DataActuador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False)),
                ('value', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id_actuator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.actuator')),
                ('id_controller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.microcontroller')),
            ],
        ),
    ]
