# Generated by Django 3.1.1 on 2020-10-28 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20201028_1255'),
        ('control', '0002_dataactuador_datasensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataactuador',
            old_name='id_actuator',
            new_name='actuator',
        ),
        migrations.RenameField(
            model_name='dataactuador',
            old_name='id_controller',
            new_name='controller',
        ),
        migrations.RenameField(
            model_name='datasensor',
            old_name='id_controller',
            new_name='controller',
        ),
        migrations.RenameField(
            model_name='datasensor',
            old_name='id_sensor',
            new_name='sensor',
        ),
        migrations.CreateModel(
            name='RegisterController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('mac_address', models.TextField(max_length=12, null=True)),
                ('controller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.microcontroller')),
            ],
        ),
    ]
