# Generated by Django 3.1.1 on 2020-10-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20201028_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercontroller',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
