# Generated by Django 3.1.1 on 2021-04-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20201028_1255'),
        ('control', '0005_auto_20201028_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logging', models.TextField(max_length=2000, null=True)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('controller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.microcontroller')),
            ],
        ),
        migrations.DeleteModel(
            name='VerificationMonitor',
        ),
    ]
