# Generated by Django 3.1.1 on 2021-04-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20210421_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='type_log',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
