# Generated by Django 3.1.1 on 2021-04-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_log_type_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasensor',
            old_name='data',
            new_name='value',
        ),
    ]
