# Generated by Django 3.2.5 on 2021-07-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20210423_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataactuador',
            name='data_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
